import {
  Flame,
  CookingPot,
  Utensils,
  Bath,
  BedDouble,
  Shirt,
  Coffee,
  Soup,
  Baby,
  UtensilsCrossed,
  Sparkles,
  ShieldAlert,
  HeartPulse,
  Car,
  ParkingCircle,
  Snowflake,
  Trees,
  Wind,
  Thermometer,
  Droplets,
  Wifi,
  CupSoda,
  ChefHat,
  CalendarRange,
  Luggage,
  Microwave,
  Sofa,
  Refrigerator,
  Blinds,
  Waves,
  AlarmSmoke,
  Music,
  Speaker,
  Tv,
  WashingMachine,
  Wine,
  Users,
  Dog,
  DoorOpen,
  Wand2,
  Cigarette,
  CigaretteOff,
  Lock,
  Key,
  KeyRound,
  Briefcase,
  Dumbbell,
  Waves as Pool,
  Mountain,
  Sun,
  Umbrella,
  Building2,
  TreePine,
  Bike,
  Camera,
  Tent,
  Flower2,
  GlassWater,
  Salad,
  EggFried,
  Bone,
  PawPrint,
  Plug,
  Zap,
  Battery,
  Lightbulb,
  Fan,
  AirVent,
  ShowerHead,
  Toilet,
  Armchair,
  Hammer,
  Wrench,
  Bell,
  BellRing,
  Eye,
  ShieldCheck,
  Shield,
  Siren,
  Radio,
  Headphones,
  MonitorPlay,
  Gamepad2,
  Dice5,
  BookOpen,
  Newspaper,
  Printer,
  Computer,
  Laptop,
  Smartphone,
  PhoneCall,
  Mail,
  MapPin,
  Compass,
  Map,
  Navigation,
  Plane,
  Train,
  Bus,
  TramFront,
  Anchor,
  Sailboat,
  CarFront,
  Caravan,
  Accessibility,
  PersonStanding,
  Heart,
  Star,
  CheckCircle2,
  Leaf,
  Sprout,
  Cloud,
  CloudRain,
  CloudSnow,
  Tornado,
  Sunset,
  Sunrise,
  Moon,
  Award,
  Trophy,
  Gift,
  PartyPopper,
  Cake,
  IceCream,
  Pizza,
  Wheat,
  Egg,
  Beef,
  Fish,
  Apple,
  Cherry,
  Croissant,
  CookieIcon,
  Beer,
  Martini,
  Citrus,
  Carrot,
  Banana,
  Grape,
  Cog,
  Settings,
  Volume2,
  Disc3,
  Film,
  Clapperboard,
  Projector,
  CircleCheck,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  // Outdoor cooking
  "bbq grill": Flame,
  "bbq": Flame,
  "barbecue": Flame,
  "barbeque": Flame,
  "baking sheet": CookingPot,
  "barbeque utensils": Utensils,
  "barbecue utensils": Utensils,
  "outdoor dining area": UtensilsCrossed,
  "fire pit": Flame,
  "patio or balcony": Sun,
  "balcony": Sun,
  "patio": Sun,

  // Bathroom
  bathtub: Bath,
  "shower gel": ShowerHead,
  shampoo: ShowerHead,
  conditioner: ShowerHead,
  "body soap": ShowerHead,
  shower: ShowerHead,
  "hot tub": Bath,
  jacuzzi: Bath,
  toilet: Toilet,
  bidet: Droplets,
  "hair dryer": Wind,
  "towels provided": ShowerHead,
  towels: ShowerHead,

  // Bedroom
  "bed linens": BedDouble,
  "extra pillows and blankets": BedDouble,
  pillows: BedDouble,
  blankets: BedDouble,
  "clothing storage": Shirt,
  closet: Shirt,
  wardrobe: Shirt,
  hangers: Shirt,
  "room-darkening shades": Blinds,
  "blackout curtains": Blinds,
  curtains: Blinds,
  iron: Wand2,
  "iron board": Wand2,

  // Kitchen / Dining
  coffee: Coffee,
  "coffee maker": Coffee,
  "espresso machine": Coffee,
  "nespresso machine": Coffee,
  cookware: Soup,
  crib: Baby,
  highchair: Baby,
  "high chair": Baby,
  "dining table": UtensilsCrossed,
  "dishes and silverware": UtensilsCrossed,
  silverware: Utensils,
  dishwasher: Sparkles,
  kettle: CupSoda,
  kitchen: ChefHat,
  "kitchenette": ChefHat,
  microwave: Microwave,
  oven: CookingPot,
  stove: Flame,
  "induction stove": Flame,
  "gas stove": Flame,
  refrigerator: Refrigerator,
  fridge: Refrigerator,
  "mini fridge": Refrigerator,
  freezer: Snowflake,
  toaster: Microwave,
  blender: Soup,
  "wine glasses": Wine,
  "champagne glasses": Martini,
  "cooking basics": ChefHat,
  "salt and pepper": Salad,
  oil: Salad,

  // Safety
  "fire extinguisher": ShieldAlert,
  "first aid kit": HeartPulse,
  "smoke detector": AlarmSmoke,
  "smoke alarm": AlarmSmoke,
  "carbon monoxide detector": Siren,
  "carbon monoxide alarm": Siren,
  "security cameras on property": Camera,
  "security cameras": Camera,
  "safe": Lock,
  "lockbox": KeyRound,
  "smart lock": Lock,
  "self check-in": Key,
  "keypad": KeyRound,

  // Cleaning
  "cleaning products": Sparkles,
  "cleaning available during stay": Sparkles,
  "self-cleaning oven": Sparkles,

  // Parking & Transport
  "free parking on premises": Car,
  "paid parking on premises": Car,
  "free parking on street": ParkingCircle,
  "paid parking off premises": ParkingCircle,
  "ev charger": Plug,
  "electric vehicle charger": Plug,
  "garage": CarFront,
  "bicycles": Bike,

  // Outdoor / Location
  "garden or backyard": Trees,
  garden: Trees,
  backyard: Trees,
  "outdoor seating (furniture)": Sofa,
  "outdoor seating": Sofa,
  "outdoor furniture": Sofa,
  "sun loungers": Sunset,
  hammock: Tent,
  "private entrance": DoorOpen,
  pool: Pool,
  "private pool": Pool,
  "shared pool": Pool,
  "infinity pool": Pool,
  "beach access": Umbrella,
  "beachfront": Umbrella,
  "ski-in/ski-out": Mountain,
  "mountain view": Mountain,
  "sea view": Waves,
  "ocean view": Waves,
  "lake view": Waves,
  "city view": Building2,

  // Climate
  heating: Thermometer,
  "central heating": Thermometer,
  "underfloor heating": Thermometer,
  "air conditioning": AirVent,
  ac: AirVent,
  "central air conditioning": AirVent,
  fan: Fan,
  "ceiling fan": Fan,
  "portable fans": Fan,
  "indoor fireplace": Flame,
  fireplace: Flame,

  // Utilities
  "hot water": Droplets,
  water: Droplets,
  electricity: Zap,
  internet: Wifi,
  wifi: Wifi,
  "wireless internet": Wifi,
  "ethernet connection": Plug,

  // Entertainment
  tv: Tv,
  "smart tv": Tv,
  "cable tv": Tv,
  "satellite tv": Tv,
  netflix: MonitorPlay,
  "sound system": Music,
  "bluetooth sound system": Music,
  "stereo system": Speaker,
  speakers: Speaker,
  "record player": Disc3,
  "books and reading material": BookOpen,
  books: BookOpen,
  "board games": Dice5,
  "game console": Gamepad2,

  // Long stay / work
  "long term stays allowed": CalendarRange,
  "luggage dropoff allowed": Luggage,
  workspace: Laptop,
  "dedicated workspace": Laptop,
  desk: Laptop,
  printer: Printer,

  // Wellness
  sauna: Waves,
  steam: ShowerHead,
  spa: HeartPulse,
  gym: Dumbbell,
  "exercise equipment": Dumbbell,
  yoga: PersonStanding,

  // Family / Pets
  "suitable for children (2-12 years)": Users,
  "suitable for infants (under 2 years)": Baby,
  "children's books and toys": Gift,
  "children's dinnerware": Utensils,
  "baby bath": Bath,
  "baby monitor": Camera,
  "babysitter recommendations": Baby,
  "changing table": Baby,
  "pets allowed": Dog,
  "pets live on property": PawPrint,

  // Smoking
  "smoking allowed": Cigarette,
  "no smoking": CigaretteOff,
  "smoke-free": CigaretteOff,

  // Accessibility
  "wheelchair accessible": Accessibility,
  "step-free access": Accessibility,
  elevator: Building2,
  lift: Building2,

  // Misc
  "host greets you": Bell,
  doorman: Bell,
  "24/7 reception": BellRing,
  concierge: BellRing,
  "essentials": Sparkles,
};

const fallbackBySubstring: Array<[string, LucideIcon]> = [
  ["wifi", Wifi],
  ["internet", Wifi],
  ["tv", Tv],
  ["coffee", Coffee],
  ["espresso", Coffee],
  ["fridge", Refrigerator],
  ["refriger", Refrigerator],
  ["freezer", Snowflake],
  ["microwave", Microwave],
  ["oven", CookingPot],
  ["stove", Flame],
  ["fire", Flame],
  ["bbq", Flame],
  ["barbe", Flame],
  ["pool", Pool],
  ["sauna", Waves],
  ["spa", HeartPulse],
  ["gym", Dumbbell],
  ["bath", Bath],
  ["shower", ShowerHead],
  ["toilet", Toilet],
  ["towel", ShowerHead],
  ["soap", ShowerHead],
  ["shampoo", ShowerHead],
  ["bed", BedDouble],
  ["pillow", BedDouble],
  ["blanket", BedDouble],
  ["linen", BedDouble],
  ["closet", Shirt],
  ["wardrobe", Shirt],
  ["hanger", Shirt],
  ["clothes", Shirt],
  ["clothing", Shirt],
  ["iron", Wand2],
  ["dryer", Wind],
  ["hair", Wind],
  ["wash", WashingMachine],
  ["laundry", WashingMachine],
  ["dish", Sparkles],
  ["clean", Sparkles],
  ["heat", Thermometer],
  ["air condition", AirVent],
  ["a/c", AirVent],
  ["fan", Fan],
  ["water", Droplets],
  ["fireplace", Flame],
  ["wine", Wine],
  ["glass", GlassWater],
  ["kitchen", ChefHat],
  ["dining", UtensilsCrossed],
  ["silverware", Utensils],
  ["utensil", Utensils],
  ["cookware", Soup],
  ["kettle", CupSoda],
  ["smoke", AlarmSmoke],
  ["carbon", Siren],
  ["camera", Camera],
  ["security", ShieldCheck],
  ["safe", Lock],
  ["lock", Lock],
  ["key", Key],
  ["check-in", Key],
  ["check in", Key],
  ["parking", Car],
  ["garage", CarFront],
  ["ev charg", Plug],
  ["charger", Plug],
  ["bike", Bike],
  ["bicycle", Bike],
  ["garden", Trees],
  ["yard", Trees],
  ["balcony", Sun],
  ["patio", Sun],
  ["terrace", Sun],
  ["beach", Umbrella],
  ["sea", Waves],
  ["ocean", Waves],
  ["lake", Waves],
  ["mountain", Mountain],
  ["view", Eye],
  ["entrance", DoorOpen],
  ["door", DoorOpen],
  ["seating", Sofa],
  ["sofa", Sofa],
  ["couch", Sofa],
  ["chair", Armchair],
  ["workspace", Laptop],
  ["desk", Laptop],
  ["printer", Printer],
  ["luggage", Luggage],
  ["long term", CalendarRange],
  ["children", Users],
  ["kid", Users],
  ["infant", Baby],
  ["baby", Baby],
  ["crib", Baby],
  ["pet", Dog],
  ["dog", Dog],
  ["cat", PawPrint],
  ["smoking", Cigarette],
  ["wheelchair", Accessibility],
  ["accessible", Accessibility],
  ["elevator", Building2],
  ["lift", Building2],
  ["sound", Music],
  ["music", Music],
  ["speaker", Speaker],
  ["stereo", Speaker],
  ["board game", Dice5],
  ["game", Gamepad2],
  ["book", BookOpen],
  ["read", BookOpen],
  ["shade", Blinds],
  ["blind", Blinds],
  ["curtain", Blinds],
  ["concierge", BellRing],
  ["reception", BellRing],
  ["host", Bell],
];

export function getAmenityIcon(name: string): LucideIcon {
  if (!name) return CheckCircle2;
  const key = name.trim().toLowerCase();
  if (map[key]) return map[key];
  for (const k of Object.keys(map)) {
    if (key.includes(k) || k.includes(key)) return map[k];
  }
  for (const [needle, icon] of fallbackBySubstring) {
    if (key.includes(needle)) return icon;
  }
  return CheckCircle2;
}
