import {
  Flame,
  CookingPot,
  Utensils,
  Bath,
  BedDouble,
  Shirt,
  Coffee,
  Soup,
  Baby,
  UtensilsCrossed,
  Sparkles,
  ShieldAlert,
  HeartPulse,
  Car,
  ParkingCircle,
  Snowflake,
  Trees,
  Wind,
  Hanger,
  Thermometer,
  Droplets,
  Wifi,
  CupSoda,
  ChefHat,
  CalendarRange,
  Luggage,
  Microwave,
  Sofa,
  Refrigerator,
  Blinds,
  Waves,
  AlarmSmoke,
  Music,
  Speaker,
  Tv,
  Square,
  WashingMachine,
  Wine,
  Users,
  Dog,
  DoorOpen,
  Package,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  "bbq grill": Flame,
  "baking sheet": CookingPot,
  "barbeque utensils": Utensils,
  "barbecue utensils": Utensils,
  bathtub: Bath,
  "bed linens": BedDouble,
  "clothing storage": Shirt,
  coffee: Coffee,
  "coffee maker": Coffee,
  cookware: Soup,
  crib: Baby,
  "dining table": UtensilsCrossed,
  "dishes and silverware": UtensilsCrossed,
  dishwasher: Sparkles,
  "fire extinguisher": ShieldAlert,
  "first aid kit": HeartPulse,
  "free parking on premises": Car,
  "free parking on street": ParkingCircle,
  freezer: Snowflake,
  "garden or backyard": Trees,
  "hair dryer": Wind,
  hangers: Hanger,
  heating: Thermometer,
  "hot water": Droplets,
  "indoor fireplace": Flame,
  internet: Wifi,
  kettle: CupSoda,
  kitchen: ChefHat,
  "long term stays allowed": CalendarRange,
  "luggage dropoff allowed": Luggage,
  microwave: Microwave,
  "outdoor seating (furniture)": Sofa,
  "outdoor seating": Sofa,
  oven: CookingPot,
  "private entrance": DoorOpen,
  refrigerator: Refrigerator,
  "room-darkening shades": Blinds,
  sauna: Waves,
  "smoke detector": AlarmSmoke,
  "sound system": Music,
  "stereo system": Speaker,
  stove: Flame,
  tv: Tv,
  "towels provided": Square,
  washer: WashingMachine,
  "wine glasses": Wine,
  "wireless internet": Wifi,
  "suitable for children (2-12 years)": Users,
  "suitable for infants (under 2 years)": Baby,
  "pets allowed": Dog,
};

export function getAmenityIcon(name: string): LucideIcon {
  if (!name) return Package;
  const key = name.trim().toLowerCase();
  if (map[key]) return map[key];
  // loose match
  for (const k of Object.keys(map)) {
    if (key.includes(k) || k.includes(key)) return map[k];
  }
  return Package;
}